// Generated with Shader Minifier 1.3.5 (https://github.com/laurentlb/Shader_Minifier/)
#ifndef FRAGMENT_INL_
# define FRAGMENT_INL_

const char *fragment_frag =
 "#version 330\n"
 "#define m1 main\n"
 "#define DEBUG_COLORS false\n"
 "uniform int m;"
 "uniform sampler2D sb1;"
 "out vec4 o1;"
 "uniform vec3 camPos,camRot;"
 "float v;"
 "vec2 M=vec2(1920,1080);"
 "vec3 t(vec3 v)"
 "{"
   "v=fract(v*vec3(.1031,.103,.0973));"
   "v+=dot(v,v.yxz+33.33);"
   "return fract((v.xxy+v.yxx)*v.zyx);"
 "}"
 "const vec3 n[28]=vec3[](vec3(.5),vec3(.5),vec3(1),vec3(0,.33,.67),vec3(.5),vec3(.5),vec3(1),vec3(0,.1,.2),vec3(.5),vec3(.5),vec3(1),vec3(.3,.2,.2),vec3(.5),vec3(.5),vec3(1,1,.5),vec3(.8,.9,.3),vec3(.5),vec3(.5),vec3(1,.7,.4),vec3(0,.15,.2),vec3(.5),vec3(.5),vec3(2,1,0),vec3(.5,.2,.25),vec3(.8,.5,.4),vec3(.2,.4,.2),vec3(2,1,1),vec3(0,.25,.25));"
 "vec3 t(float v,vec3 y,vec3 x,vec3 B,vec3 M)"
 "{"
   "return y+x*cos(6.28318*(B*v+M));"
 "}"
 "vec3 t(float v,int m)"
 "{"
   "int B=m*4;"
   "return t(v,n[B],n[B+1],n[B+2],n[B+3]);"
 "}"
 "vec3 B=vec3(1,20./255.,147./255.)*.2,f=vec3(1,.2,.2);\n"
 "#define PI 3.14159265\n"
 "#define TAU (2*PI)\n"
 "#define PHI (sqrt(5)*0.5+0.5)\n"
 "#define saturate(x)clamp(x,0,1)\n"
 "float t(vec3 v,vec3 y,float x)"
 "{"
   "vec3 n=abs(v)-y+x;"
   "return length(max(n,0.))+min(max(n.x,max(n.y,n.z)),0.)-x;"
 "}"
 "const vec3 N[19]=vec3[](normalize(vec3(1,0,0)),normalize(vec3(0,1,0)),normalize(vec3(0,0,1)),normalize(vec3(1)),normalize(vec3(-1,1,1)),normalize(vec3(1,-1,1)),normalize(vec3(1,1,-1)),normalize(vec3(0,1,PHI+1)),normalize(vec3(0,-1,PHI+1)),normalize(vec3(PHI+1,0,1)),normalize(vec3(-PHI-1,0,1)),normalize(vec3(1,PHI+1,0)),normalize(vec3(-1,PHI+1,0)),normalize(vec3(0,PHI,1)),normalize(vec3(0,-PHI,1)),normalize(vec3(1,0,PHI)),normalize(vec3(-1,0,PHI)),normalize(vec3(PHI,1,0)),normalize(vec3(-PHI,1,0)));"
 "float t(inout float v,float n)"
 "{"
   "float y=n*.5,B=floor((v+y)/n);"
   "v=mod(v+y,n)-y;"
   "return B;"
 "}"
 "float e(float v,float n,float y)"
 "{"
   "return min(-y,max(v,n))+length(max(vec2(y+v,y+n),vec2(0)));"
 "}\n"
 "#define MAX_STEPS 250\n"
 "#define MAX_DIST 80.\n"
 "#define INFTY (MAX_DIST*2)\n"
 "#define SURF_DIST.005\n"
 "#define NORMAL_EPSILON SURF_DIST*0.1\n"
 "#define TWO_PI 6.28318530718\n"
 "#define G_ANG 2.39996322973\n"
 "#define GAMMA (1.0/2.2)\n"
 "#define AA 1\n"
 "#define LIGHT_COUNT 3\n"
 "#define SAMPLE_RATE 44100\n"
 "#define BPM 166.000000\n"
 "#define MAX_INSTRUMENTS 7\n"
 "#define MAX_PATTERNS 121\n"
 "#define PATTERN_SIZE_SHIFT 4\n"
 "#define PATTERN_SIZE (1<<PATTERN_SIZE_SHIFT)\n"
 "#define MAX_TICKS (MAX_PATTERNS*PATTERN_SIZE)\n"
 "#define SAMPLES_PER_TICK 3984\n"
 "#define MAX_SAMPLES (SAMPLES_PER_TICK*MAX_TICKS)\n"
 "#define BEAT_TIME (60.0/BPM)\n"
 "#define MAX_BEATS 120.0\n"
 "#define MAX_TIME (BPM*MAX_BEATS)\n"
 "vec3 r=vec3(0);"
 "vec3 e()"
 "{"
   "vec3 f;"
   "f.x=v/(4.*BEAT_TIME);"
   "f.y=v/BEAT_TIME;"
   "f.z=v/MAX_TIME;"
   "return f;"
 "}\n"
 "#define I(x)(int(floor(x)))\n"
 "#define BAR0 (audioProgress.x)\n"
 "#define BAR1 (audioProgress.x+1.0)\n"
 "#define BAR_PROGRESS fract(BAR0)\n"
 "#define WHOLE_NOTE 1.\n"
 "#define HALF_NOTE 2.\n"
 "#define QUARTER_NOTE 4.\n"
 "#define EIGHTH_NOTE 8.\n"
 "#define SIXTEENTH_NOTE 16.\n"
 "#define NOTE0(d)(BAR_PROGRESS*d)\n"
 "#define NOTE1(d)(NOTE0(d)+1.0)\n"
 "#define BEAT0 NOTE0(QUARTER_NOTE)\n"
 "#define BEAT1 NOTE1(QUARTER_NOTE)\n"
 "vec3 d[LIGHT_COUNT]=vec3[LIGHT_COUNT](vec3(15,10,-10)*.9,vec3(-10,15,10)*.9,vec3(10,-10,15)*.9);"
 "vec2 e(vec3 v,vec3 n,vec3 y,float x)"
 "{"
   "vec3 f=v-y;"
   "float B=dot(f,n),d=B*B-dot(f,f)+x*x;"
   "if(d<0.)"
     "return vec2(-1);"
   "d=sqrt(d);"
   "return vec2(-B-d,-B+d);"
 "}\n"
 "#define GRID_SIZE 2.5\n"
 "#define BOX_SIZE 0.75\n"
 "#define BOX_ROUNDNESS 0.1\n"
 "float y=1.;"
 "float s(vec3 x,out vec3 f,out vec3 B)"
 "{"
   "f=x;"
   "float d=length(x)-6.;"
   "vec3 m=vec3(.3,.4,.5)*v;"
   "f.x+=m.x;"
   "float n=t(f.x,GRID_SIZE),i=round(mod(abs(n),2.));"
   "if(i==1.)"
     "m.y*=-1.;"
   "f.y+=m.y;"
   "float M=t(f.y,GRID_SIZE);"
   "i=round(mod(abs(M),2.));"
   "if(i==1.)"
     "m.z*=-1.;"
   "f.z+=m.z;"
   "float S=t(f.z,GRID_SIZE);"
   "B=vec3(n,M,S);"
   "vec3 s=t(B*vec3(3,5,7));"
   "float N=floor(s.x*3.),z=t(f,vec3(BOX_SIZE*y),BOX_ROUNDNESS);"
   "if(N==0.)"
     "z=GRID_SIZE/2.-BOX_SIZE*y;"
   "float r=e(d,z,BOX_ROUNDNESS*0.);"
   "r=max(d,z);"
   "return r;"
 "}"
 "float s(vec3 v)"
 "{"
   "return s(v,mappedPosition,cs);"
 "}"
 "float S=acos(-1.);"
 "vec3 e(vec3 v)"
 "{"
   "return v-floor(v*(1./289.))*289.;"
 "}"
 "vec4 e(vec4 v)"
 "{"
   "return v-floor(v*(1./289.))*289.;"
 "}"
 "vec4 s(vec4 v)"
 "{"
   "return e((v*34.+10.)*v);"
 "}"
 "float i(vec3 v)"
 "{"
   "const vec2 n=vec2(1./6.,1./3.);"
   "const vec4 B=vec4(0,.5,1,2);"
   "vec3 f=floor(v+dot(v,n.yyy)),d=v-f+dot(f,n.xxx),y=step(d.yzx,d.xyz),m=1.-y,z=min(y.xyz,m.zxy),P=max(y.xyz,m.zxy),x=d-z+n.xxx,i=d-P+n.yyy,M=d-B.yyy;"
   "f=e(f);"
   "vec4 N=s(s(s(f.z+vec4(0,z.z,P.z,1))+f.y+vec4(0,z.y,P.y,1))+f.x+vec4(0,z.x,P.x,1));"
   "vec3 S=.142857142857*B.wyz-B.xzx;"
   "vec4 r=N-49.*floor(N*S.z*S.z),E=floor(r*S.z),G=E*S.x+S.yyyy,T=floor(r-7.*E)*S.x+S.yyyy,w=1.-abs(G)-abs(T),c=vec4(G.xy,T),t=vec4(G.zw,T.zw),o=-step(w,vec4(0)),a=c.xzyw+(floor(c)*2.+1.).xzyw*o.xxyy,Q=t.xzyw+(floor(t)*2.+1.).xzyw*o.zzww;"
   "vec3 A=vec3(a.xy,w),u=vec3(a.zw,w.y),D=vec3(Q.xy,w.z),K=vec3(Q.zw,w.w);"
   "vec4 p=1.79284291400159-.85373472095314*vec4(dot(A,A),dot(u,u),dot(D,D),dot(K,K));"
   "A*=p.x;"
   "u*=p.y;"
   "D*=p.z;"
   "K*=p.w;"
   "vec4 l=max(.5-vec4(dot(d,d),dot(x,x),dot(i,i),dot(M,M)),0.);"
   "l*=l;"
   "return 105.*dot(l*l,vec4(dot(A,d),dot(u,x),dot(D,i),dot(K,M)));"
 "}"
 "void e(inout vec3 v,float f)"
 "{"
   "float n=cos(f),y=sin(f);"
   "v.xz=mat2(n,y,-y,n)*v.xz;"
 "}"
 "void i(inout vec3 v,float f)"
 "{"
   "float n=cos(f),y=sin(f);"
   "v.xy=mat2(n,y,-y,n)*v.xy;"
 "}"
 "void s(inout vec3 v,float f)"
 "{"
   "float n=cos(f),y=sin(f);"
   "v.yz=mat2(n,y,-y,n)*v.yz;"
 "}"
 "vec3 x(vec3 v)"
 "{"
   "return B;"
 "}"
 "vec3 x(vec3 v,vec3 y,vec3 f)"
 "{"
   "vec3 n=t(f*vec3(2,3,5));"
   "return t(floor(n.x*3.)/3.,5)*.25;"
 "}"
 "float i(vec3 v,vec3 y,out vec3 n,out vec3 f)"
 "{"
   "float B=0.;"
   "for(int r=0;r<MAX_STEPS;r++)"
     "{"
       "vec3 d=v+y*B;"
       "float x=s(d,n,f);"
       "B+=.3*x;"
       "if(B>MAX_DIST||x<SURF_DIST)"
         "break;"
     "}"
   "return B;"
 "}"
 "vec3 p(vec3 v)"
 "{"
   "float B=s(v);"
   "vec2 f=vec2(NORMAL_EPSILON,0);"
   "vec3 n=B-vec3(s(v-f.xyy),s(v-f.yxy),s(v-f.yyx));"
   "return normalize(n);"
 "}"
 "float e(vec3 v,vec3 y,float f,float x,float n)"
 "{"
   "float d=1.,B=f;"
   "for(int r=0;r<256&&B<x;r++)"
     "{"
       "float i=s(v+B*y);"
       "d=min(d,i/(n*B));"
       "B+=clamp(i,.005,.5);"
       "if(d<-1.||B>x)"
         "break;"
     "}"
   "d=max(d,-1.);"
   "return.25*(1.+d)*(1.+d)*(2.-d);"
 "}"
 "vec3 c(vec3 f)"
 "{"
   "vec3 n=vec3(.1,.2,.3)*v;"
   "float B=sqrt(sqrt(i(f*67.+n)));"
   "B=max(0.,B-.95)*10.;"
   "return t(.5+B*.8,4);"
 "}"
 "void c()"
 "{"
   "r=e();"
   "float n=.1;"
   "for(int f=0;f<LIGHT_COUNT;++f)"
     "s(d[f],v*n),n+=.1,e(d[f],v*n),n+=.1,i(d[f],v*n);"
   "if(fract(BAR0/8.)>=.5)"
     "y=1.3;"
 "}"
 "void m1()"
 "{"
   "v=m/44100.;"
   "c();"
   "vec3 f=vec3(0),n=vec3(0);"
   "\n#if AA>1\n"
   "for(int B=0;B<AA;B++)"
     "for(int r=0;r<AA;r++)"
       "{"
         "\n#else\n"
         "\n#endif\n"
         "vec2 y=(gl_FragCoord.xy+vec2(0)-M.xy/2)/M.y;"
         "vec3 N=camPos,z=vec3(y,1);"
         "s(z,-camRot.y);"
         "e(z,-camRot.x);"
         "z=normalize(z);"
         "vec3 S=N,P,E;"
         "float A=i(N,z,P,E);"
         "bool G=false;"
         "for(int T=0;T<LIGHT_COUNT;++T)"
           "{"
             "vec2 t=e(N,z,d[T],1.2);"
             "G=G||t.x>=0.&&t.x<A;"
           "}"
         "if(G)"
           "f=vec3(1);"
         "else if(A>MAX_DIST)"
           "f=c(z);"
         "else"
           "{"
             "S=N+z*A;"
             "vec3 t=vec3(0),T=vec3(0);"
             "for(int o=0;o<LIGHT_COUNT;++o)"
               "{"
                 "vec3 w=normalize(d[o]-S),D=p(S);"
                 "float l=dot(D,w);"
                 "f=x(S,P,E);"
                 "float a=pow(clamp(dot(normalize(-w+2.*l*D),-z),0.,1.),50.),K=1.2*2/pow(length(d[o]-S),1.),u=e(S,w,SURF_DIST*2.,MAX_DIST,K),Q=2.3/LIGHT_COUNT;"
                 "t+=Q*(1.-a)*(normalize(vec3(.4,.3,1))*length(vec3(1))*.23+.77*l*vec3(1))*u;"
                 "T+=a*vec3(1)*u;"
               "}"
             "f*=t;"
             "f+=T;"
             "f=pow(f,vec3(GAMMA));"
           "}"
         "n+=f;"
         "\n#if AA>1\n"
       "}"
   "n/=float(AA*AA);"
   "\n#endif\n"
   "if(DEBUG_COLORS)"
     "n=vec3(floor(NOTE0(EIGHTH_NOTE))/4.);"
   "min(n.x,min(n.y,n.z))>=.8;"
   "o1=vec4(n,1);"
 "}"
 "void m2()"
 "{"
   "v=m/44100.;"
   "vec2 n=gl_FragCoord.xy/M.xy;"
   "vec3 f=vec3(0);"
   "vec2 B=vec2(.005,0);"
   "f.x+=texture(sb1,n-B).x;"
   "f.y+=texture(sb1,n).y;"
   "f.z+=texture(sb1,n+B).z;"
   "o1=vec4(f*10.,1);"
   "o1=vec4(2);"
 "}";

#endif // FRAGMENT_INL_
