// Generated with Shader Minifier 1.3.5 (https://github.com/laurentlb/Shader_Minifier/)
#ifndef FRAGMENT_INL_
# define FRAGMENT_INL_

const char *fragment_frag =
 "#version 330\n"
 "#define m1 main\n"
 "uniform int m;"
 "uniform sampler2D sb1;"
 "out vec4 o1;"
 "uniform vec3 camPos,camRot;"
 "float v;"
 "vec2 M=vec2(1920,1080);"
 "vec3 t(vec3 v)"
 "{"
   "v=fract(v*vec3(.1031,.103,.0973));"
   "v+=dot(v,v.yxz+33.33);"
   "return fract((v.xxy+v.yxx)*v.zyx);"
 "}"
 "const vec3 n[28]=vec3[](vec3(.5),vec3(.5),vec3(1),vec3(0,.33,.67),vec3(.5),vec3(.5),vec3(1),vec3(0,.1,.2),vec3(.5),vec3(.5),vec3(1),vec3(.3,.2,.2),vec3(.5),vec3(.5),vec3(1,1,.5),vec3(.8,.9,.3),vec3(.5),vec3(.5),vec3(1,.7,.4),vec3(0,.15,.2),vec3(.5),vec3(.5),vec3(2,1,0),vec3(.5,.2,.25),vec3(.8,.5,.4),vec3(.2,.4,.2),vec3(2,1,1),vec3(0,.25,.25));"
 "vec3 t(float v,vec3 x,vec3 y,vec3 B,vec3 M)"
 "{"
   "return x+y*cos(6.28318*(B*v+M));"
 "}"
 "vec3 t(float v,int m)"
 "{"
   "int B=m*4;"
   "return t(v,n[B],n[B+1],n[B+2],n[B+3]);"
 "}"
 "vec3 S=vec3(1,20./255.,147./255.)*.2,f=vec3(1,.2,.2);\n"
 "#define PI 3.14159265\n"
 "#define TAU (2*PI)\n"
 "#define PHI (sqrt(5)*0.5+0.5)\n"
 "#define saturate(x)clamp(x,0,1)\n"
 "float t(vec3 v,vec3 x,float M)"
 "{"
   "vec3 n=abs(v)-x+M;"
   "return length(max(n,0.))+min(max(n.x,max(n.y,n.z)),0.)-M;"
 "}"
 "const vec3 B[19]=vec3[](normalize(vec3(1,0,0)),normalize(vec3(0,1,0)),normalize(vec3(0,0,1)),normalize(vec3(1)),normalize(vec3(-1,1,1)),normalize(vec3(1,-1,1)),normalize(vec3(1,1,-1)),normalize(vec3(0,1,PHI+1)),normalize(vec3(0,-1,PHI+1)),normalize(vec3(PHI+1,0,1)),normalize(vec3(-PHI-1,0,1)),normalize(vec3(1,PHI+1,0)),normalize(vec3(-1,PHI+1,0)),normalize(vec3(0,PHI,1)),normalize(vec3(0,-PHI,1)),normalize(vec3(1,0,PHI)),normalize(vec3(-1,0,PHI)),normalize(vec3(PHI,1,0)),normalize(vec3(-PHI,1,0)));"
 "float t(inout float v,float n)"
 "{"
   "float x=n*.5,f=floor((v+x)/n);"
   "v=mod(v+x,n)-x;"
   "return f;"
 "}"
 "float e(float v,float n,float x)"
 "{"
   "return min(-x,max(v,n))+length(max(vec2(x+v,x+n),vec2(0)));"
 "}\n"
 "#define MAX_STEPS 250\n"
 "#define MAX_DIST 80.\n"
 "#define INFTY (MAX_DIST*2)\n"
 "#define SURF_DIST.005\n"
 "#define NORMAL_EPSILON SURF_DIST*0.1\n"
 "#define TWO_PI 6.28318530718\n"
 "#define G_ANG 2.39996322973\n"
 "#define GAMMA (1.0/2.2)\n"
 "#define AA 1\n"
 "#define LIGHT_COUNT 3\n"
 "#define SAMPLE_RATE 44100\n"
 "#define BPM 166.000000\n"
 "#define MAX_INSTRUMENTS 7\n"
 "#define MAX_PATTERNS 121\n"
 "#define PATTERN_SIZE_SHIFT 4\n"
 "#define PATTERN_SIZE (1<<PATTERN_SIZE_SHIFT)\n"
 "#define MAX_TICKS (MAX_PATTERNS*PATTERN_SIZE)\n"
 "#define SAMPLES_PER_TICK 3984\n"
 "#define MAX_SAMPLES (SAMPLES_PER_TICK*MAX_TICKS)\n"
 "#define BEAT_TIME (60.0/BPM)\n"
 "#define MAX_BEATS 120.0\n"
 "#define MAX_TIME (BPM*MAX_BEATS)\n"
 "vec3 N=vec3(0);\n"
 "#define I(x)(int(floor(x)))\n"
 "#define BAR0 (audioProgress.x)\n"
 "#define BAR1 (audioProgress.x+1.0)\n"
 "#define BAR_PROGRESS fract(BAR0)\n"
 "#define WHOLE_NOTE 1.\n"
 "#define HALF_NOTE 2.\n"
 "#define QUARTER_NOTE 4.\n"
 "#define EIGHTH_NOTE 8.\n"
 "#define SIXTEENTH_NOTE 16.\n"
 "#define NOTE0(d)(BAR_PROGRESS*d)\n"
 "#define NOTE1(d)(NOTE0(d)+1.0)\n"
 "#define BEAT0 NOTE0(QUARTER_NOTE)\n"
 "#define BEAT1 NOTE1(QUARTER_NOTE)\n"
 "vec3 d[LIGHT_COUNT]=vec3[LIGHT_COUNT](vec3(15,10,-10)*.9,vec3(-10,15,10)*.9,vec3(10,-10,15)*.9);"
 "vec2 e(vec3 v,vec3 n,vec3 x,float M)"
 "{"
   "vec3 d=v-x;"
   "float m=dot(d,n),f=m*m-dot(d,d)+M*M;"
   "if(f<0.)"
     "return vec2(-1);"
   "f=sqrt(f);"
   "return vec2(-m-f,-m+f);"
 "}\n"
 "#define GRID_SIZE 2.5\n"
 "#define BOX_SIZE 0.75\n"
 "#define BOX_ROUNDNESS 0.1\n"
 "float r(vec3 x,out vec3 f,out vec3 M)"
 "{"
   "f=x;"
   "float B=length(x)-6.;"
   "vec3 m=vec3(.3,.4,.5)*v;"
   "f.x+=m.x;"
   "float d=t(f.x,GRID_SIZE),n=round(mod(abs(d),2.));"
   "if(n==1.)"
     "m.y*=-1.;"
   "f.y+=m.y;"
   "float y=t(f.y,GRID_SIZE);"
   "n=round(mod(abs(y),2.));"
   "if(n==1.)"
     "m.z*=-1.;"
   "f.z+=m.z;"
   "float P=t(f.z,GRID_SIZE);"
   "M=vec3(d,y,P);"
   "vec3 i=t(M*vec3(3,5,7));"
   "float N=floor(i.x*3.),z=t(f,vec3(BOX_SIZE),BOX_ROUNDNESS);"
   "if(N==0.)"
     "z=GRID_SIZE/2.-BOX_SIZE;"
   "float r=e(B,z,BOX_ROUNDNESS*0.);"
   "r=max(B,z);"
   "return r;"
 "}"
 "float r(vec3 v)"
 "{"
   "return r(v,mappedPosition,cs);"
 "}"
 "float P=acos(-1.);"
 "vec3 e(vec3 v)"
 "{"
   "return v-floor(v*(1./289.))*289.;"
 "}"
 "vec4 e(vec4 v)"
 "{"
   "return v-floor(v*(1./289.))*289.;"
 "}"
 "vec4 r(vec4 v)"
 "{"
   "return e((v*34.+10.)*v);"
 "}"
 "float s(vec3 v)"
 "{"
   "const vec2 n=vec2(1./6.,1./3.);"
   "const vec4 M=vec4(0,.5,1,2);"
   "vec3 f=floor(v+dot(v,n.yyy)),d=v-f+dot(f,n.xxx),x=step(d.yzx,d.xyz),P=1.-x,m=min(x.xyz,P.zxy),z=max(x.xyz,P.zxy),y=d-m+n.xxx,i=d-z+n.yyy,B=d-M.yyy;"
   "f=e(f);"
   "vec4 N=r(r(r(f.z+vec4(0,m.z,z.z,1))+f.y+vec4(0,m.y,z.y,1))+f.x+vec4(0,m.x,z.x,1));"
   "vec3 S=.142857142857*M.wyz-M.xzx;"
   "vec4 s=N-49.*floor(N*S.z*S.z),c=floor(s*S.z),E=c*S.x+S.yyyy,G=floor(s-7.*c)*S.x+S.yyyy,T=1.-abs(E)-abs(G),a=vec4(E.xy,G),o=vec4(E.zw,G.zw),t=-step(T,vec4(0)),Q=a.xzyw+(floor(a)*2.+1.).xzyw*t.xxyy,A=o.xzyw+(floor(o)*2.+1.).xzyw*t.zzww;"
   "vec3 w=vec3(Q.xy,T),u=vec3(Q.zw,T.y),K=vec3(A.xy,T.z),b=vec3(A.zw,T.w);"
   "vec4 p=1.79284291400159-.85373472095314*vec4(dot(w,w),dot(u,u),dot(K,K),dot(b,b));"
   "w*=p.x;"
   "u*=p.y;"
   "K*=p.z;"
   "b*=p.w;"
   "vec4 l=max(.5-vec4(dot(d,d),dot(y,y),dot(i,i),dot(B,B)),0.);"
   "l*=l;"
   "return 105.*dot(l*l,vec4(dot(w,d),dot(u,y),dot(K,i),dot(b,B)));"
 "}"
 "void e(inout vec3 v,float d)"
 "{"
   "float n=cos(d),f=sin(d);"
   "v.xz=mat2(n,f,-f,n)*v.xz;"
 "}"
 "void r(inout vec3 v,float d)"
 "{"
   "float n=cos(d),f=sin(d);"
   "v.xy=mat2(n,f,-f,n)*v.xy;"
 "}"
 "void s(inout vec3 v,float d)"
 "{"
   "float n=cos(d),f=sin(d);"
   "v.yz=mat2(n,f,-f,n)*v.yz;"
 "}"
 "vec3 x(vec3 v)"
 "{"
   "return S;"
 "}"
 "vec3 x(vec3 v,vec3 x,vec3 d)"
 "{"
   "vec3 f=t(d*vec3(2,3,5));"
   "return t(floor(f.x*3.)/3.,5)*.25;"
 "}"
 "float r(vec3 v,vec3 x,out vec3 n,out vec3 d)"
 "{"
   "float f=0.;"
   "for(int B=0;B<MAX_STEPS;B++)"
     "{"
       "vec3 y=v+x*f;"
       "float M=r(y,n,d);"
       "f+=.3*M;"
       "if(f>MAX_DIST||M<SURF_DIST)"
         "break;"
     "}"
   "return f;"
 "}"
 "vec3 p(vec3 v)"
 "{"
   "float m=r(v);"
   "vec2 f=vec2(NORMAL_EPSILON,0);"
   "vec3 d=m-vec3(r(v-f.xyy),r(v-f.yxy),r(v-f.yyx));"
   "return normalize(d);"
 "}"
 "float e(vec3 v,vec3 x,float f,float d,float n)"
 "{"
   "float M=1.,y=f;"
   "for(int B=0;B<256&&y<d;B++)"
     "{"
       "float m=r(v+y*x);"
       "M=min(M,m/(n*y));"
       "y+=clamp(m,.005,.5);"
       "if(M<-1.||y>d)"
         "break;"
     "}"
   "M=max(M,-1.);"
   "return.25*(1.+M)*(1.+M)*(2.-M);"
 "}"
 "vec3 c(vec3 d)"
 "{"
   "vec3 M=vec3(.1,.2,.3)*v;"
   "float f=sqrt(sqrt(s(d*67.+M)));"
   "f=max(0.,f-.95)*10.;"
   "return t(.5+f*.8,4);"
 "}"
 "void c()"
 "{"
   "float n=.1;"
   "for(int f=0;f<LIGHT_COUNT;++f)"
     "s(d[f],v*n),n+=.1,e(d[f],v*n),n+=.1,r(d[f],v*n);"
 "}"
 "void m1()"
 "{"
   "v=m/44100.;"
   "c();"
   "vec3 f=vec3(0),n=vec3(0);"
   "\n#if AA>1\n"
   "for(int B=0;B<AA;B++)"
     "for(int y=0;y<AA;y++)"
       "{"
         "\n#else\n"
         "\n#endif\n"
         "vec2 i=(gl_FragCoord.xy+vec2(0)-M.xy/2)/M.y;"
         "vec3 N=camPos,z=vec3(i,1);"
         "s(z,-camRot.y);"
         "e(z,-camRot.x);"
         "z=normalize(z);"
         "vec3 P=N,T,E;"
         "float S=r(N,z,T,E);"
         "bool a=false;"
         "for(int A=0;A<LIGHT_COUNT;++A)"
           "{"
             "vec2 t=e(N,z,d[A],1.2);"
             "a=a||t.x>=0.&&t.x<S;"
           "}"
         "if(a)"
           "f=vec3(1);"
         "else if(S>MAX_DIST)"
           "f=c(z);"
         "else"
           "{"
             "P=N+z*S;"
             "vec3 A=vec3(0),G=vec3(0);"
             "for(int w=0;w<LIGHT_COUNT;++w)"
               "{"
                 "vec3 o=normalize(d[w]-P),K=p(P);"
                 "float l=dot(K,o);"
                 "f=x(P,T,E);"
                 "float t=pow(clamp(dot(normalize(-o+2.*l*K),-z),0.,1.),50.),b=1.2*2/pow(length(d[w]-P),1.),u=e(P,o,SURF_DIST*2.,MAX_DIST,b),Q=2.3/LIGHT_COUNT;"
                 "A+=Q*(1.-t)*(normalize(vec3(.4,.3,1))*length(vec3(1))*.23+.77*l*vec3(1))*u;"
                 "G+=t*vec3(1)*u;"
               "}"
             "f*=A;"
             "f+=G;"
             "f=pow(f,vec3(GAMMA));"
           "}"
         "n+=f;"
         "\n#if AA>1\n"
       "}"
   "n/=float(AA*AA);"
   "\n#endif\n"
   "o1=vec4(n,1);"
 "}"
 "void m2()"
 "{"
   "return;"
 "}";

#endif // FRAGMENT_INL_
